-- turret factory tech level 51+ blueprinting and manufacture enabler code.
-- by rglx
-- allows all turret factories at level 50 (within a few sectors of 0:0) to manufacture and blueprint boss-dropped turrets of tech level 51 & 52

-- leave this here. tells avorion's script-loading engine which part of the game this is.
-- namespace TurretFactory

-- re-word the UI title because it was bothering me, also, any factories higher than 50 are essentially max-levelled so we should reflect that, and conceal the fact that the balancing wont allow any tech levels higher than 50 unless specifically generated by the game e.g. dropped by a dead boss.
function TurretFactory.onShowWindow()
	if TurretFactory.getTechLevel() > 49 then -- overriding it to make sure people know that anything 50 and up is max-levelled.
		window.caption = "Turret Factory - Tech Level: Max"
	else
		window.caption = "Turret Factory - Tech Level: " .. TurretFactory.getTechLevel()
	end

	if buildTurretsTab.isActiveTab then
		TurretFactory.refreshBuildTurretsUI()
	else
		TurretFactory.refreshMakeBlueprintsUI()
	end
end

 -- this was remarkably simple. the turrets don't actually REACH tech level 52 because the balancing won't actually LET it. This function's only called in the above (now overwritten) UI related function and in the two checks to see if a turret can be manufactured or blueprinted by this factory.
function TurretFactory.getTechLevel()
	local x, y = TurretFactory.getCoordinates()
	local tech = Balancing_GetTechLevel(x, y)
	if tech > 49 then
		return 52 -- just override it to return 52 because that's the max tech level in the game.
	else
		return tech -- ... unless it's not a tech-level 50+ factory
	end
end
print("rglx-TL51+BPs: Tech Levels 51+ allowed for vanilla blueprinting and manufacture")